
import java.awt.Font;
import java.awt.event.KeyEvent;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JPanel;
import net.i2p.client.streaming.I2PSocket;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author LU$er
 */
public class Chat_Window extends JPanel 
{
    
    private ObjectOutputStream OOS ;
    private ObjectInputStream OIS ;
    private I2PSocket i2psock ;
    
    // Variables declaration - do not modify                     
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton Button0 ;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    public static javax.swing.JTextArea jTextArea2;
    // End of variables declaration   
    private String Name;
                
    
    
    public Chat_Window ( String x, ObjectOutputStream OOS, ObjectInputStream OIS, I2PSocket i2psock ) 
    {
        Name = x ;
        this.OOS = OOS ;
        this.OIS = OIS ;
        this.i2psock = i2psock ;
        // **** 
        initComponents ( ) ; 
        // ****
        jTextArea2.setFont(new Font("Serif", Font.BOLD, 16));
        jTextArea2.setLineWrap(true);
        jTextArea2.setWrapStyleWord(true);
    }
    
    
    
    
    
    public static void Refresh_Area ( String e, String name )
    {
        Date date = new Date ( ) ;
        DateFormat sdf = new SimpleDateFormat ( "HH:mm" ) ;
        jTextArea2.append ( sdf.format ( date ) + name + ": " + e + "\n" ) ;
        System.out.println ( " D" ) ;  
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() 
    {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        Button0 = new javax.swing.JButton();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("");
        jTextArea1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                try 
                {
                    jTextArea1KeyPressed(evt);
                } 
                catch (IOException ex) 
                {
                    try
                    {
                      jTextArea2.setText ( " " ) ;
                      jTextArea2.setText ( "Closing Chat." ) ;
                      System.out.println ( "prin" ) ;
                      setVisible ( false ) ;
                      System.out.println ( "meta" ) ;
                      OIS.close ( ) ;
                      OOS.close ( ) ;
                      i2psock.close ( ) ;
                      //Logger.getLogger(Chat_Window.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    catch ( IOException f )
                    {
                     //Nothing   
                    }
                }
            }
        });
        jScrollPane1.setViewportView(jTextArea1);

        jLabel1.setText(Name);

        jTextArea2.setBackground(new java.awt.Color(255, 255, 255));
        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);
        
        Button0.setBackground(new java.awt.Color(255, 51, 51));
        Button0.setText("X");
        Button0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed ( java.awt.event.ActionEvent evt ) 
            {
                Button0ActionPerformed( evt ) ;
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout ( this ) ;
        this.setLayout(layout);
        layout.setHorizontalGroup
        (
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Button0))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2)))
                .addContainerGap())
        );
        layout.setVerticalGroup
        (
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addComponent(Button0)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>         
    
    
    private void Button0ActionPerformed (java.awt.event.ActionEvent evt ) 
    {                                         
        // TODO add your handling code here:
        //Close Chat
        try
        {
          this.OOS.close ( ) ;
          this.OIS.close ( ) ;
          this.i2psock.close ( ) ;
          this.setVisible ( false ) ;
          this.removeAll ( ) ;
        }
        catch ( IOException OIE )
        {
            
        }
    }
    
    
    
    
   
    
    
    
    private void jTextArea1KeyPressed ( java.awt.event.KeyEvent evt ) throws IOException 
    {                                      
        // TODO add your handling code here:
        int key = evt.getKeyCode ( ) ;
        if ( key == KeyEvent.VK_ENTER ) 
        {
           //send message to Friend
            String t =  jTextArea1.getText ( ) ;
                try
                {
                Date date = new Date ( ) ;
                DateFormat sdf = new SimpleDateFormat ( "HH:mm" ) ;
                jTextArea2.append ( sdf.format ( date ) + "Me: " + t + "\n" ) ;
                this.OOS.writeObject ( new Message ( t ) ) ;  //send him your message
                this.OOS.flush ( ) ;
                System.out.println ( "D" ) ;
                jTextArea1.setText ( "" ) ;
                jTextArea1.setAutoscrolls ( false ) ;
                }
                catch ( IOException IOE )
                {
                    jTextArea2.setText ( " " ) ;
                    jTextArea2.setText ( "Closing Chat." ) ;
                    this.setVisible ( false ) ;
                    this.OIS.close ( ) ;
                    this.OOS.close ( ) ;
                    this.i2psock.close ( ) ;
                }
        }
     }
}
